### PR TITLE
Fixed build on case-sensitive fs. Xcode 10.2 compatible (has SipHash warnings)

### PR DESCRIPTION
**Pull request by ypopovych**

### CODE REVIEW

**Comment by Ybrin** [comment]
Great, thanks. Just make sure the travis build succeeds so I can merge it safely...

**Comment by ypopovych** [comment]
Will check. Seems as new Swift brought some problems. It uses non-optional initializers by default.

**Comment by TG908** [comment]
https://github.com/apple/swift-evolution/blob/master/proposals/0213-literal-init-via-coercion.md this is the issue. I already fixed it in #46

**Comment by ypopovych** [comment]
@TG908 I think we should merge both PRs into one.

**Comment by ypopovych** [comment]
@Ybrin @TG908 I will close this PR. I checked what @TG908 did, and his PR is better. We can merge it, and close this and #50

**Pull request closed without merging**
