### PR TITLE
improve Decimal conversion performance using `_mantissa`

### PR DESCRIPTION
**Pull request by mredig**
> There seems to be a public-ish field called `_mantissa` in `Decimal` which should be faster than using the string representation here. Maybe we should use this and keep the above arround maybe commented out just in case `_mantissa` goes away one day.

_Originally posted by @tgymnich in https://github.com/attaswift/BigInt/pull/123#discussion_r1833119142_

According to my tests, it looks like using the `_mantissa` approach is roughly 1/3 faster.

```
Starting 'Decimal String Init' with 999999 iterations.
Test 'Decimal String Init' with 999999 iterations took 14.572233080863953 seconds.
Finished 'Decimal String Init' with 999999 iterations.


Starting 'Decimal Mantissa Init' with 999999 iterations.
Test 'Decimal Mantissa Init' with 999999 iterations took 10.257248044013977 seconds.
Finished 'Decimal Mantissa Init' with 999999 iterations.


╔═══════════════════════╤══════════════╤══════════════╤══════════════╤══════════════╤══════════════╗
║ Label                 │ Avg          │ Max          │ Min          │ Delta        │ Median       ║
╟───────────────────────┼──────────────┼──────────────┼──────────────┼──────────────┼──────────────╢
║ Decimal Mantissa Init │ 0.0000102246 │ 0.0002379417 │ 0.0000089407 │ 0.0002290010 │ 0.0000110865 ║
╟───────────────────────┼──────────────┼──────────────┼──────────────┼──────────────┼──────────────╢
║ Decimal String Init   │ 0.0000144051 │ 0.0035669804 │ 0.0000129938 │ 0.0035539865 │ 0.0000140667 ║
╚═══════════════════════╧══════════════╧══════════════╧══════════════╧══════════════╧══════════════╝
```

I'll have another push in a bit to address the second suggestion.

### CODE REVIEW

**Comment by mredig** [comment]
Oh well look at that - linux doesn't like optimizations! Apparently "public-ish" was more on point than I thought.

**Comment by mredig** [comment]
> Works, but setting the remaining bytes (`0..<i`) to zero after the loop below could be more efficient.

_Originally posted by @tgymnich in https://github.com/attaswift/BigInt/pull/123#discussion_r1833127664_

✅

**Comment by mredig** [comment]
Bonus - I realized I needed `Decimal(_ value: Big(U)Int` and added that. I might be able to figure out a mantissa init instead of string based, but brain now dead. 🧟

**Review by tgymnich — APPROVED** [review]
👍

**Pull request merged**
