### PR TITLE
Let Swift Package Manager support Linux, too

### PR DESCRIPTION
**Pull request by dankogai**
With this PR you can `swift build` and `swift test` on Linux.
Note `SipHash` needs fixes as https://github.com/attaswift/SipHash/pull/6 so for the time being its url is pointed to https://github.com/dankogai/SipHash .

### CODE REVIEW

**Comment by dankogai** [comment]
No response for about two weeks.  Would you have a look?  I need this module on Linux!

**Comment by Ybrin** [comment]
Could you give me push access to your fork? There are a few things I want to fix before merging it.

**Comment by Ybrin** [comment]
I will still either need push access or you have to base your PR against a new branch `fix/linux`. There are a few things we can't add into the production version...

**Comment by Ybrin** [comment]
`SipHash` is fine. Just for `BigInt` please

**Comment by dankogai** [comment]
Sorry it took a little while.  Now you have push access, too.

**Comment by Ybrin** [comment]
Merged and released

**Comment by Ybrin** [comment]
Thanks for your efforts @dankogai

**Pull request merged**
